apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CreateVOIPMigrationWorkOrder
  description: |
    This is a technical service used to facilitate the Migration process (by creating a work order) for the customers from 'TDM' telephony service to the Voice over Cable (VoC) service. It also updates the Customer Migration status in MIDAS after attempting to create the Migration Workorder.
spec:
  type: openapi
  owner: Developer
  lifecycle: demo
  system: Fixed Line
  definition:
    $text: https://github.com/baludeepak7/CreateWorKorder_V3/blob/main/createvoipmigrationworkorder.yaml
    
